blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord server
    url: https://discord.gg/2SUWKFnHSm
    about: Chat with the project community.
  - name: ðŸ—¨ Discussions
    url: https://github.com/Tyrrrz/CliFx/discussions/new
    about: Ask and answer questions.